name: edge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
      - ./logs:/var/log/nginx
    networks:
      - edge
    restart: always

networks:
  edge:
    external: true
    name: ${EDGE_NETWORK_NAME:-edge_web}
